baseurl = "https://borgengutta.github.io"
publishDir = "docs"
languageCode = "nb-no"
DefaultContentLanguage = "nb"
#DefaultContentLanguage = "en"
title = "Borgen Gutta"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Borgen Gutta" # Set a different text for the header on the home page
  subtitle = "Nyhet og informasjonsdelingsside for Borgen G2006/G2005."
  mainSections = ["post","posts"]
  logo = "img/BorgenIL_Logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jan Vidar Elven"
  website = "borgen-il.no"
  email = "borgengutta@live.com"
  facebook = "borgenil.no"
  github = "borgengutta"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "OfficialBorgen"
  #reddit = "username"
  linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  instagram = "borgen_il"
  youtube = "channel/UCc3bA0ngtF7z9YN30B4TIxw" # "user/username" or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "egentrening"
    name = "Egentrening"
    weight = 2

[[menu.main]]
    parent = "egentrening"
    name = "Egentrening 2020"
    url = "page/egentrening2020"
    weight = 3

[[menu.main]]
    parent = "egentrening"
    name = "Egentrening 2021"
    url = "page/egentrening2021"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
